import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

import Nav from '@/components/Nav';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/Satoshi/Satoshi-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi/Satoshi-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi/Satoshi-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi/Satoshi-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi/Satoshi-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
});

export const metadata = {
  title: 'Tegathon',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.className} ${inter.className}`}>
        <main className="relative">
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
