import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const satoshi_variable = localFont({
  src: "../public/fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi-variable",
  display: "swap",
});

export const metadata = {
  title: "Tegathon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${satoshi_variable.className} ${inter.className} ${satoshi_variable.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
